### ISSUE TITLE
Donor Contact Information

### ISSUE THREAD

**Issue by rbrtmnz** [WorkingFamilies/crm#12] opened 2019-02-06 21:55 UTC
**Detailed Description**
Please include contact information as fields in reports. We are going to use this to pull fundraising reports so we need the ability to pull reports with contact info.

**Urgency**
2

**Comment by codygordon** [comment] 2019-04-29 21:03
duplicate of https://github.com/WorkingFamilies/crm/issues/15

**Closed by codygordon** 2019-04-29 21:03 UTC
Labels: enhancement
